### PR TITLE
data sources: Make cdc and disorder non-optional, default values; remove with_source

### PR DESCRIPTION
**Pull request by mohitreddy1996**

### CODE REVIEW

**Comment by aditya-nambiar** [comment]
@mohitreddy1996 if you already in this code can you make the changes to CDC and disorder ( from optional to non optional types )

**Comment by mohitreddy1996** [comment]
@aditya-nambiar done! PTAL :)

**Comment by aditya-nambiar** [comment]
@mohitreddy1996 can you since param to the docs too

**Comment by mohitreddy1996** [comment]
@aditya-nambiar done!

**Comment by zsid60** [comment]
@mohitreddy1996 sorry for the duplicate work

There's still some value to what you have in PR: disorder/ CDC being mandatory, `since` documentation and some other fixes you've made. So let's keep this open / merge this? I rebased it off of main and resolved merge conflicts.

@aditya-nambiar this looks pretty ready afaict, do you want to take a look and approve it?

**Review by aditya-nambiar — APPROVED** [review]

**Pull request merged**
